=== CSang0/LMGSI_03/Mejorpelicula.dtd
<!-- DTD created at Mon Feb 04 21:08:31 CET 2019 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT mejorpelicula (anyo+)>

<!ELEMENT anyo (Pelicula+)>

<!ATTLIST anyo anyo CDATA #REQUIRED>


<!ELEMENT Pelicula (TituloOriginal, TituloEspanyol, Director, Companyia, Produccion, Genero, F_Estreno, Ganadora)>
<!ATTLIST Pelicula nombre CDATA #REQUIRED>

<!ELEMENT TituloOriginal (#PCDATA)>
<!ELEMENT TituloEspanyol (#PCDATA)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Companyia (#PCDATA)>
<!ELEMENT Produccion (#PCDATA)>
<!ELEMENT Genero (#PCDATA)>
<!ELEMENT F_Estreno (#PCDATA)>
<!ELEMENT Ganadora (#PCDATA)>

=== CSang0/LMGSI_03/MejorPelicula.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE mejorpelicula SYSTEM "Mejorpelicula.dtd">

<mejorpelicula>
	<anyo anyo="2017">
		<Pelicula nombre="The Shape of Water">
			<TituloOriginal>The Shape of Water
			</TituloOriginal>
			<TituloEspanyol>La forma del agua
			</TituloEspanyol>
			<Director>Guillermo del Toro
			</Director>
			<Companyia>Double Dare You Productions, TSG Productions, Fox Searchlight Pictures
			</Companyia>
			<Produccion>Guillermo del Toro, J. Miles Dale
			</Produccion>
			<Genero>Fantasia / Romance
			</Genero>
			<F_Estreno>2017-12-17
			</F_Estreno>	
			<Ganadora> Si
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Call Me by Your Name">
			<TituloOriginal>Call Me by Your Name
			</TituloOriginal>
			<TituloEspanyol>Llamame por tu nombre
			</TituloEspanyol>
			<Director>Luca Guadagnino
			</Director>
			<Companyia>Frensy Film Company, La Cin√®facture, RT Features, Water's End Productions
			</Companyia>
			<Produccion>Luca Guadagnino, Emilie Georges, James Ivory, Marco Morabito, Howard Rosenman, Peter Spears, Rodrigo Teixeira
			</Produccion>
			<Genero>Drama romantico
			</Genero>	
			<F_Estreno>2017-01-22
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Darkest Hour">
			<TituloOriginal>Darkest Hour
			</TituloOriginal>
			<TituloEspanyol>El instante mas oscuro
			</TituloEspanyol>
			<Director>Joe Wright
			</Director>
			<Companyia>Perfect World Pictures, Working Title Films
			</Companyia>
			<Produccion>Tim Bevan, Lisa Bruce, Eric Fellner, Anthony McCarten, Douglas Urbanski
			</Produccion>
			<Genero>Cine biografico/ Cine belico
			</Genero>	
			<F_Estreno>2017-09-01
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Dunkirk">
			<TituloOriginal>Dunkirk
			</TituloOriginal>
			<TituloEspanyol>Dunkerque
			</TituloEspanyol>
			<Director>Christopher Nolan
			</Director>
			<Companyia>Syncopy Inc.
			</Companyia>
			<Produccion>Emma Thomas, Christopher Nolan
			</Produccion>
			<Genero>Cine belico
			</Genero>	
			<F_Estreno>2017-07-21
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Get Out">
			<TituloOriginal>Get Out
			</TituloOriginal>
			<TituloEspanyol>Dejame salir
			</TituloEspanyol>
			<Director>Jordan Peele
			</Director>
			<Companyia>Blumhouse Productions, Monkeypaw Productions, QC Entertainment
			</Companyia>
			<Produccion>Sean McKittrick, Jason Blum, Edward H. Hamm Jr., Jordan Peele
			</Produccion>
			<Genero>Terror
			</Genero>	
			<F_Estreno>2017-01-23
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Lady Bird">
			<TituloOriginal>Lady Bird
			</TituloOriginal>
			<TituloEspanyol>Lady Bird
			</TituloEspanyol>
			<Director>Greta Gerwig
			</Director>
			<Companyia>Scott Rudin Productions, Management 360, IAC Films
			</Companyia>
			<Produccion>Eli Bush, Evelyn O'Neil, Scott Rudin
			</Produccion>
			<Genero>Comedia dramatica
			</Genero>	
			<F_Estreno>2017-09-01
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Phantom Thread">
			<TituloOriginal>Phantom Thread
			</TituloOriginal>
			<TituloEspanyol>El hilo invisible
			</TituloEspanyol>
			<Director>Paul Thomas Anderson
			</Director>
			<Companyia>Annapurna Pictures, Ghoulardi Film Company, Perfect World Pictures
			</Companyia>
			<Produccion>Paul Thomas Anderson, Megan Ellison, JoAnne Sellar, Daniel Lupi
			</Produccion>
			<Genero>Romance/ drama
			</Genero>	
			<F_Estreno>2017-12-25
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="The Post">
			<TituloOriginal>The Post
			</TituloOriginal>
			<TituloEspanyol>Los archivos del Pentagono
			</TituloEspanyol>
			<Director>Steven Spielberg
			</Director>
			<Companyia>Amblin Entertainment, DreamWorks, Amblin Partners, 20th Century Fox, articipant Media 
Pascal Pictures, Star Thrower Entertainment
			</Companyia>
			<Produccion>Steven Spielberg, Kristie Macosko Krieger, Amy Pascal
			</Produccion>
			<Genero>Thriller/ Drama/ Cine biografico/ Cine historico
			</Genero>	
			<F_Estreno>2017-12-14
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Three Billboards Outside Ebbing, Missouri">
			<TituloOriginal>Three Billboards Outside Ebbing, Missouri
			</TituloOriginal>
			<TituloEspanyol>Tres anuncios en las afueras
			</TituloEspanyol>
			<Director>Martin McDonagh
			</Director>
			<Companyia>Film4 Productions, Fox Searchlight Pictures, Blueprint Pictures
			</Companyia>
			<Produccion>Graham Broadbent, Martin McDonagh, Peter Czernin
			</Produccion>
			<Genero>Drama/ humor negro/ misterio
			</Genero>	
			<F_Estreno>2017-11-10
			</F_Estreno>	
			<Ganadora> No
			</Ganadora>		
		</Pelicula>
	</anyo>
	<anyo anyo="2016" >
		<Pelicula nombre="Moonlight">
			<TituloOriginal> Moonlight
			</TituloOriginal>
			<TituloEspanyol> Luz de Luna
			</TituloEspanyol>
			<Director>Barry Jenkins
			</Director>
			<Companyia>A24
Plan B Entertainment
Pastel Productions
			</Companyia>
			<Produccion>Adele Romanski
Dede Gardner
Jeremy Kleiner
			</Produccion>
			<Genero> Drama
			</Genero>	
			<F_Estreno>2016-09-02
			</F_Estreno>	
			<Ganadora> Si
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Arrival">
			<TituloOriginal> Arrival
			</TituloOriginal>
			<TituloEspanyol>	La llegada
			</TituloEspanyol>
			<Director> Denis Villeneuve
			</Director>
			<Companyia>	FilmNation Entertainment
21 Laps Entertainment
Lava Bear Films
			</Companyia>
			<Produccion>	Dan Levine
Shawn Levy
David Linde
Aaron Ryder
			</Produccion>
			<Genero>	Ciencia ficcion
			</Genero>	
			<F_Estreno>2016-09-01
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Fences">
			<TituloOriginal>Fences
			</TituloOriginal>
			<TituloEspanyol>Fences
			</TituloEspanyol>
			<Director>	
Denzel Washington
			</Director>
			<Companyia>	Macro
Bron Studios
Scott Rudin Productions
			</Companyia>
			<Produccion>	Todd Black
Scott Rudin
Denzel Washington
			</Produccion>
			<Genero>Drama
			</Genero>	
			<F_Estreno>2016-12-25
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Hacksaw Ridge">
			<TituloOriginal>Hacksaw Ridge
			</TituloOriginal>
			<TituloEspanyol>
Titulo	Hasta el ultimo hombre 
			</TituloEspanyol>
			<Director>	
Mel Gibson
			</Director>
			<Companyia>Cross Creek Pictures
Pandemonium Films
Permut Productions
Vendian Entertainment
Demarest Media
Kilburn Media
			</Companyia>
			<Produccion>	Paul Currie
Bruce Davey
William D. Johnson
Bill Mechanic
Brian Oliver
David Permut
Terry Benedict
			</Produccion>
			<Genero>	Belico
Biografico
			</Genero>	
			<F_Estreno>2016-11-23
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Hell or High Water">
			<TituloOriginal>Hell or High Water
			</TituloOriginal>
			<TituloEspanyol>Comancheria 
			</TituloEspanyol>
			<Director>	
David Mackenzie
			</Director>
			<Companyia>	Sidney Kimmel Entertainment
OddLot Entertainment
Film 44
LBI Entertainment
			</Companyia>
			<Produccion>	Sidney Kimmel
Peter Berg
Carla Hacken
Julie Yorn
Gigi Pritzker
Rachel Shane
Braden Aftergood
			</Produccion>
			<Genero>	Policial
Thriller
			</Genero>	
			<F_Estreno>2016-08-12
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Hidden Figures">
			<TituloOriginal>Hidden Figures
			</TituloOriginal>
			<TituloEspanyol>	Figuras ocultas
			</TituloEspanyol>
			<Director>	
Theodore Melfi
			</Director>
			<Companyia>	
20th Century Fox
Chernin Entertainment
Donna Gigliotti
TSG Entertainment
			</Companyia>
			<Produccion>	
Donna Gigliotti
Peter Chernin
Jenno Topping
Pharrell Williams
Theodore Melfi
			</Produccion>
			<Genero>	Biografica, drama
			</Genero>	
			<F_Estreno>2016-12-25
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="La La Land">
			<TituloOriginal>La La Land
			</TituloOriginal>
			<TituloEspanyol>	La Ciudad De Las Estrellas: La La Land 
			</TituloEspanyol>
			<Director>	
Damien Chazelle
			</Director>
			<Companyia>	Summit Entertainment
Black Label Media
TIK Films
Impostor Pictures
Gilbert Films
Marc Platt Productions
			</Companyia>
			<Produccion>	Fred Berger
Gary Gilbert
Jordan Horowitz
Marc Platt
			</Produccion>
			<Genero>	Musical
Romance
Drama
			</Genero>	
			<F_Estreno>2016-08-31
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Lion">
			<TituloOriginal>Lion
			</TituloOriginal>
			<TituloEspanyol>Lion
			</TituloEspanyol>
			<Director>	
Garth Davis
			</Director>
			<Companyia>	
See-Saw Films
Aquarius Films
Screen Australia
Sunstar Entertainment
The Weinstein Company
			</Companyia>
			<Produccion>	
Iain Canning
Angie Fielder
Emile Sherman
			</Produccion>
			<Genero>	Drama
			</Genero>	
			<F_Estreno>2016-09-10
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
		<Pelicula nombre="Manchester by the Sea">
			<TituloOriginal>Manchester by the Sea
			</TituloOriginal>
			<TituloEspanyol>Manchester frente al mar 
			</TituloEspanyol>
			<Director>	
Kenneth Lonergan
			</Director>
			<Companyia>	B Story
CMP
K Period Media
Pearl Street Films
The A / Middleton Project
			</Companyia>
			<Produccion>	Lauren Beck
Matt Damon
Chris Moore
Kimberly Steward
Kevin J. Walsh
			</Produccion>
			<Genero>	Drama
			</Genero>	
			<F_Estreno>2016-01-23
			</F_Estreno>	
			<Ganadora>No
			</Ganadora>		
		</Pelicula>
	</anyo>
	<anyo anyo="2015">
		<Pelicula nombre="Spotlight">
			<TituloOriginal>Spotlight
